name: Test Flutter App

on: [push]

jobs:
  build:
    name: Test Flutter App
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Say start a build
        run: echo flutter build web
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"

      - name: Run a flutter build and deploy
        working-directory: ./flutter_app
        run: |
          flutter config --enable-web
          flutter pub get
          flutter test
